name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Unit Test
        run: make race
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./artifacts/coverage.txt
          flags: unittests
          name: codecov-umbrella
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Build Environment
        run: make up
      - name: Fetch Logs
        run: make logs
      - name: Integration Test
        run: make integration
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --issues-exit-code=1